### ISSUE TITLE
train_data目录的数据来源？

### ISSUE THREAD

**Issue by WernGin** [liuhuanyong/ChineseEmbedding#1]
@liuhuanyong  您好！ 您只提到使用中文维基百科的语料进行训练。能指出"train_data"的数据来源么？

**Comment by liuhuanyong** [comment]
@WernGin 您好，各类向量都是以中文维基百科语料训练而来，只是做了相应的转换，如拼音转换，依存句法分析等，分别形成相应的训练文件。

**Comment by WernGin** [comment]
好的。那我先试试吧。感谢～
